name: CI

on:
  - push

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: brew install gtk+3 gtkmm3 gtk-mac-integration adwaita-icon-theme libsigc++ little-cms2 libiptcdata fftw lensfun llvm expat pkgconfig libomp
    - name: cmake
      env:
        CMAKE_CXX_STANDARD: 11
        PKG_CONFIG_PATH: /usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/expat/lib/pkgconfig
        RAW_THERAPEE_MAJOR: '5'
        RAW_THERAPEE_MINOR: '7'
      run: |
        mkdir build && cd build
        cmake \
          -DCMAKE_BUILD_TYPE="release" \
          -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
          -DCACHE_NAME_SUFFIX="${RAW_THERAPEE_MAJOR}.${RAW_THERAPEE_MINOR}-${GITHUB_REF##*/}" \
          -DPROC_TARGET_NUMBER="2" \
          -DPROC_LABEL="generic processor" \
          -DWITH_LTO="OFF" \
          -DLENSFUNDBDIR="./share/lensfun" \
          -DOpenMP_C_FLAGS=-fopenmp=libomp \
          -DOpenMP_CXX_FLAGS=-fopenmp=libomp \
          -DOpenMP_C_LIB_NAMES="libomp" \
          -DOpenMP_CXX_LIB_NAMES="libomp" \
          -DOpenMP_libomp_LIBRARY="/usr/local/lib/libomp.dylib" \
          -DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp /usr/local/lib/libomp.dylib -I/usr/local/include" \
          -DOpenMP_CXX_LIB_NAMES="libomp" \
          -DOpenMP_C_FLAGS="-Xpreprocessor -fopenmp /usr/local/lib/libomp.dylib -I/usr/local/include" \
          ..
        make --jobs 8
        make install
        make macosx_bundle
